default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 172.17.0.1

development:
  <<: *default
  database: escuela_development

test:
  <<: *default
  database: escuela_test

production:
  <<: *default
  database: escuela_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
